{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"s:8NIOHTTP20A6ErrorsO24PushInViolationOfSettingV8locationSSvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"NIOHTTP2"}],"symbolKind":"property","title":"location","role":"symbol","roleHeading":"Instance Property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Linux"]}]}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting"]]},"abstract":[{"text":"The location where the error was thrown.","type":"text"}],"variants":[{"paths":["\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location","interfaceLanguage":"swift"},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting":{"url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting","title":"NIOHTTP2Errors.PushInViolationOfSetting","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushInViolationOfSetting","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An attempt was made to push a stream, even though the settings forbid it."}],"kind":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting","navigatorTitle":[{"text":"PushInViolationOfSetting","kind":"identifier"}],"type":"topic"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors":{"url":"\/documentation\/niohttp2\/niohttp2errors","title":"NIOHTTP2Errors","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NIOHTTP2Errors","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","abstract":[{"type":"text","text":"Errors that NIO raises when handling HTTP\/2 connections."}],"navigatorTitle":[{"text":"NIOHTTP2Errors","kind":"identifier"}]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"url":"\/documentation\/niohttp2","title":"NIOHTTP2","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","abstract":[]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting/location":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location","role":"symbol","kind":"symbol","abstract":[{"text":"The location where the error was thrown.","type":"text"}],"title":"location"}}}