{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError"},"metadata":{"role":"symbol","modules":[{"name":"NIOCore"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"title":"ByteToMessageDecoderError","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"ByteToMessageDecoderError"}],"externalID":"s:7NIOCore25ByteToMessageDecoderErrorO","symbolKind":"enum"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niocore\/bytetomessagedecodererror"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/co.pointfree.VaporRouting\/s5ErrorP","doc:\/\/co.pointfree.VaporRouting\/s8SendableP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ByteToMessageDecoderError","kind":"identifier"}],"languages":["swift"],"platforms":["Linux"]}]}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore"]]},"topicSections":[{"identifiers":["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/PayloadTooLargeError"],"title":"Structures"},{"title":"Enumeration Cases","identifiers":["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/leftoverDataWhenDone(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Common errors thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}],"references":{"doc://co.pointfree.VaporRouting/s8SendableP":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/PayloadTooLargeError":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/PayloadTooLargeError","title":"ByteToMessageDecoderError.PayloadTooLargeError","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PayloadTooLargeError"}],"navigatorTitle":[{"kind":"identifier","text":"PayloadTooLargeError"}],"url":"\/documentation\/niocore\/bytetomessagedecodererror\/payloadtoolargeerror","abstract":[{"type":"text","text":"This error can be thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s if the incoming payload is larger than the max specified."}]},"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"title":"NIOCore","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","abstract":[],"url":"\/documentation\/niocore","type":"topic","kind":"symbol","role":"collection"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError","title":"ByteToMessageDecoderError","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"navigatorTitle":[{"kind":"identifier","text":"ByteToMessageDecoderError"}],"url":"\/documentation\/niocore\/bytetomessagedecodererror","abstract":[{"type":"text","text":"Common errors thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}]},"doc://co.pointfree.VaporRouting/s5ErrorP":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/leftoverDataWhenDone(_:)":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/leftoverDataWhenDone(_:)","title":"ByteToMessageDecoderError.leftoverDataWhenDone(_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftoverDataWhenDone"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer"},{"kind":"text","text":")"}],"url":"\/documentation\/niocore\/bytetomessagedecodererror\/leftoverdatawhendone(_:)","abstract":[{"type":"text","text":"This error can be thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s if there was unexpectedly some left-over data when the"},{"type":"text","text":" "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":" was removed from the pipeline or the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" was closed."}]},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer"},{"kind":"text","text":")"}],"url":"\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)","abstract":[{"type":"text","text":"More data has been received by a "},{"type":"codeVoice","code":"ByteToMessageHandler"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" is the error previously emitted and the "},{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" has been sent through the pipeline using "},{"type":"codeVoice","code":"fireErrorCaught"},{"type":"text","text":"."}]}}}