{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedServerError"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"NIOWebSocket"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"WebSocketErrorCode.unexpectedServerError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unexpectedServerError","kind":"identifier"}],"externalID":"s:12NIOWebSocket03WebB9ErrorCodeO016unexpectedServerD0yA2CmF"},"kind":"symbol","sections":[],"abstract":[{"text":"Indicates that a server is terminating the connection because","type":"text"},{"text":" ","type":"text"},{"text":"it encountered an unexpected condition that prevented it from","type":"text"},{"text":" ","type":"text"},{"text":"fulfilling the request.","type":"text"},{"text":" ","type":"text"},{"text":"Corresponds to code 1011.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOWebSocket","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOWebSocket\/WebSocketErrorCode"]]},"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOWebSocket\/WebSocketErrorCode\/unexpectedServerError","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niowebsocket\/websocketerrorcode\/unexpectedservererror"]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOWebSocket/WebSocketErrorCode":{"kind":"symbol","navigatorTitle":[{"text":"WebSocketErrorCode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOWebSocket\/WebSocketErrorCode","abstract":[{"type":"text","text":"An enum that represents websocket error codes."}],"title":"WebSocketErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WebSocketErrorCode","kind":"identifier"}],"url":"\/documentation\/niowebsocket\/websocketerrorcode","type":"topic"},"doc://co.pointfree.VaporRouting/documentation/NIOWebSocket":{"abstract":[],"url":"\/documentation\/niowebsocket","kind":"symbol","role":"collection","title":"NIOWebSocket","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOWebSocket","type":"topic"},"doc://co.pointfree.VaporRouting/documentation/NIOWebSocket/WebSocketErrorCode/unexpectedServerError":{"url":"\/documentation\/niowebsocket\/websocketerrorcode\/unexpectedservererror","kind":"symbol","abstract":[{"type":"text","text":"Indicates that a server is terminating the connection because"},{"type":"text","text":" "},{"type":"text","text":"it encountered an unexpected condition that prevented it from"},{"type":"text","text":" "},{"type":"text","text":"fulfilling the request."},{"type":"text","text":" "},{"type":"text","text":"Corresponds to code 1011."}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOWebSocket\/WebSocketErrorCode\/unexpectedServerError","type":"topic","title":"WebSocketErrorCode.unexpectedServerError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedServerError"}],"role":"symbol"}}}